# Generated by Django 5.1.6 on 2025-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
