# Generated by Django 5.1.6 on 2025-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_usuario_remove_roteiro_local_roteiro_locais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
