# Generated by Django 5.2 on 2025-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_destinofavorito_delete_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='local',
            field=models.CharField(max_length=255),
        ),
    ]
