# Generated by Django 5.1.6 on 2025-04-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_roteiro_custo_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lembrete',
        ),
    ]
