# Generated by Django 5.1.6 on 2025-04-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_delete_lembrete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programacao',
            unique_together={('roteiro', 'dia', 'horario')},
        ),
    ]
