# Generated by Django 5.2 on 2025-04-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_alter_programacao_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='feito',
            new_name='concluido',
        ),
    ]
