# Generated by Django 5.1.6 on 2025-04-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_interface_remove_roteiro_usuario_delete_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roteiro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
