# Generated by Django 5.1.6 on 2025-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_alter_programacao_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='alimentacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='extras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='hospedagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='passagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='passeios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
