# Generated by Django 5.1.6 on 2025-04-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_delete_roteiro_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interface',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
