# Generated by Django 5.2 on 2025-04-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0005_alter_interface_nome_alter_interface_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('data_ida', models.DateField()),
                ('data_volta', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='interface',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacoes', to='Interface.roteiro')),
            ],
        ),
    ]
