name: Build and deploy Python app to Azure Web App - NextStop

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment, install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Rodando testes Django (opcional, mas recomendado)
      - name: Run Django Tests
        run: |
          source venv/bin/activate
          python manage.py migrate
          python manage.py test

      - name: Clean sensitive and local files
        run: |
          rm -f db.sqlite3
          rm -f .env

      - name: Zip artifact for deployment
        run: |
          cd NextStop/
          zip -r ../release.zip ./
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_03E6A7A508DE4CAE9A169BAA550060E9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5FEBF80184C451A92C1E94E0115A719 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78B09E30F7AF4C48BB15304781D6CE6C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'NextStop'
          slot-name: 'Production'
          package: release.zip
